language: python
python:
    - "2.7"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
script:
- platformio ci teensy --board=teensy31
